-- Stored daily summaries (per user and per team), generated by aggregating
-- synced sessions. One row per (team, scope, scope_id, day). Like the other
-- tables, RLS is enabled with no policies: only the server admin key reaches it.

CREATE TABLE daily_summaries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  scope TEXT NOT NULL CHECK (scope IN ('user', 'team')),
  scope_id UUID NOT NULL,                       -- user_id for 'user', team_id for 'team'
  day DATE NOT NULL,
  summary TEXT NOT NULL,
  model TEXT,                                    -- NULL = rule-based fallback
  session_count INTEGER NOT NULL DEFAULT 0,     -- staleness check within the day
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (team_id, scope, scope_id, day)
);

CREATE INDEX daily_summaries_lookup_idx ON daily_summaries (team_id, day);

CREATE TRIGGER daily_summaries_updated_at
  BEFORE UPDATE ON daily_summaries
  FOR EACH ROW
  EXECUTE FUNCTION system.update_updated_at();

ALTER TABLE daily_summaries ENABLE ROW LEVEL SECURITY;
